###
@FILENAME = 33
###
HEAD http://localhost:4000/file/{{FILENAME}}.mp4

###
POST http://localhost:4000/file/{{FILENAME}}.mp4?blockSize=1&nodeCount=2
Content-Type: video/mp4
Transfer-Encoding: chunked

< ../videos/stream.mp4

### 55s
POST http://localhost:4000/file/avatar.mp4?blockSize=24&nodeCount=2
Content-Type: video/mp4
Transfer-Encoding: chunked

< ../videos/avatar.mp4

###
POST http://localhost:4000/file/rica.mp4?blockSize=16&nodeCount=2
Content-Type: video/mp4
Transfer-Encoding: chunked

< ../videos/costa-rica.mp4

###
GET http://localhost:4000/file/{{FILENAME}}.mp4

###
GET http://localhost:4000/file/{{FILENAME}}.mp4
Range: bytes=0-4049576