###
@FILENAME = 25
###
HEAD http://localhost:4000/file/{{FILENAME}}.mp4

###
POST http://localhost:4000/file/{{FILENAME}}.mp4?blockSize=1&nodeCount=1
Content-Type: video/mp4
Transfer-Encoding: chunked

< ../stream.mp4

###
GET http://localhost:4000/file/{{FILENAME}}.mp4

###
GET http://localhost:4000/file/{{FILENAME}}.mp4
Range: blocks=1-