version: '3.8'
services:
  data-node:
    scale: 2
    image: node:23-alpine
    working_dir: /usr/app
    labels:
      lab2-container: data-node
    ports: ["3000"]
    volumes:
      - type: volume
        target: /usr/blocks
      - type: bind
        source: .
        target: /usr/app
        read_only: true
    command: ['npm', 'run', 'start:data-node']
    environment:
      NODE_ENV: production
      BLOCKS_PATH: /usr/blocks
      PORT: 3000
    mem_limit: 80M
    cpus: 0.2
  name-node:
    image: node:23-alpine
    working_dir: /usr/app
    labels:
      lab2-container: name-node
    ports: ["4000:4000", "9229:9229"]
    volumes:
      - type: bind
        source: .
        target: /usr/app
    command: ['npm', 'run', 'start:name-node']
    environment:
      NODE_ENV: production
      PORT: 4000
      DOCKER_DAEMON: "http://host.docker.internal:2375"
      CONTAINER_URL_PREFIX: "http://host.docker.internal:"
    mem_limit: 80M
    cpus: 0.4
